name: fidelway
description: A flutter app for Qatar World Cup

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.20
  http:
  expandable: ^5.0.1
  flutter_dash: ^0.0.1
  percent_indicator: ^4.0.1
  shared_preferences: ^2.0.15
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  after_layout: ^1.2.0


analyzer:
  - enable-experiment:
      - non-nullable

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - images/


  fonts:

    - family: Popin
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: QatarBold
      fonts:
        - asset: fonts/Qatar2022Arabic-Bold.ttf

    - family: QatarHeavy
      fonts:
        - asset: fonts/Qatar2022Arabic-Heavy.ttf


